# Generated by Django 4.2.9 on 2024-05-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_member_payment_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='users.member'),
        ),
    ]
