# Generated by Django 4.2.9 on 2024-05-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_members', to='users.member'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
