# Generated by Django 4.2.9 on 2024-05-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_member_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
    ]
