# Generated by Django 4.2.9 on 2024-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_pictures'),
        ),
    ]
