# Generated by Django 4.2.9 on 2024-05-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
    ]
