# Generated by Django 4.2.9 on 2024-05-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='pic/'),
        ),
    ]
