# Generated by Django 4.2.9 on 2024-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
