# Generated by Django 4.2.9 on 2024-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_member_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='personal_archived',
            field=models.BooleanField(default=False),
        ),
    ]
