# Generated by Django 4.2.9 on 2024-05-18 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_member_personal_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedMemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('unarchived_date', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
                ('unarchived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unarchived_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
