# Generated by Django 4.2.9 on 2024-05-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_archivedmemberhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='made_by_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile'),
        ),
    ]
