# Generated by Django 4.2.9 on 2024-05-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_payment_made_by_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='made_by_user_profile',
        ),
    ]
