# Generated by Django 4.2.9 on 2024-05-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_payment_made_by_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.userprofile'),
        ),
    ]
