# Generated by Django 4.2.9 on 2024-05-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_attendance_user_profile_payment_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='member',
        ),
        migrations.CreateModel(
            name='UserProfilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half-Yearly'), ('annual', 'Annual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.userprofile')),
            ],
        ),
    ]
