# Generated by Django 4.2.9 on 2024-05-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_attendance_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilepayment',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_members', to='users.member'),
        ),
        migrations.DeleteModel(
            name='UserProfileAttendance',
        ),
        migrations.DeleteModel(
            name='UserProfilePayment',
        ),
    ]
