# Generated by Django 4.2.9 on 2024-05-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_archivedpayment_archivedattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpayment',
            name='member',
        ),
        migrations.DeleteModel(
            name='ArchivedAttendance',
        ),
        migrations.DeleteModel(
            name='ArchivedPayment',
        ),
    ]
