# Generated by Django 4.2.9 on 2024-05-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_archivedpayment_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='unique_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
