# Generated by Django 4.2.9 on 2024-05-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_payment_receipt_id_alter_member_unique_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('DOB', models.DateField(null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('medical_history', models.CharField(max_length=250, null=True)),
                ('unique_number', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pic/')),
                ('archived', models.BooleanField(default=False)),
                ('personal_archived', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='users.userprofile')),
            ],
        ),
    ]
