# Generated by Django 4.2.9 on 2024-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_role_subaccount_delete_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('assistant', 'Assistant')], max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
