# Generated by Django 4.2.9 on 2024-05-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_subaccount_role_delete_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAccount',
        ),
    ]
