# Generated by Django 4.2.9 on 2024-05-22 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_delete_subaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_members', models.BooleanField(default=True)),
                ('can_manage_payments', models.BooleanField(default=True)),
                ('can_manage_attendance', models.BooleanField(default=True)),
                ('parent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprofiles', to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
