# Generated by Django 4.2.9 on 2024-05-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_subprofile_bio_subprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='member',
        ),
    ]
