# Generated by Django 4.2.9 on 2024-05-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_subprofile_bio_remove_subprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subprofile',
            name='can_manage_attendance',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='can_manage_members',
        ),
        migrations.RemoveField(
            model_name='subprofile',
            name='can_manage_payments',
        ),
    ]
