# Generated by Django 4.2.9 on 2024-05-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_subprofile_can_manage_attendance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubProfile',
        ),
    ]
