# Generated by Django 4.2.9 on 2024-05-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_subprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubProfile',
        ),
    ]
