# Generated by Django 4.2.9 on 2024-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_delete_subprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
