# Generated by Django 4.1.13 on 2024-06-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20, null=True),
        ),
    ]
