# Generated by Django 4.1.13 on 2024-06-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_payment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
