# Generated by Django 4.1.13 on 2024-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reg_no',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
