# Generated by Django 4.2.9 on 2024-06-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_partial',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
