# Generated by Django 4.2.9 on 2024-06-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_remove_payment_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('holding', 'Holding')], default='pending', max_length=10),
        ),
    ]
