# Generated by Django 4.2.9 on 2024-06-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='custom_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='programme',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength training', 'Strength Training'), ('strength training & cardio', 'Strength Training & Cardio'), ('personal training', 'Personal Training')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half-Yearly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.CreateModel(
            name='Medical_and_personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('exercise_history', models.CharField(blank=True, max_length=300, null=True)),
                ('medications', models.CharField(blank=True, max_length=500, null=True)),
                ('surgeries', models.CharField(blank=True, max_length=400, null=True)),
                ('heart_disease', models.CharField(blank=True, max_length=500, null=True)),
                ('medical_history', models.CharField(max_length=250, null=True)),
                ('allergies', models.BooleanField(default=False)),
                ('blood_pressure', models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('normal', 'Normal')], max_length=100, null=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('arthritis', models.CharField(blank=True, choices=[('no', 'No'), ('ligament_injuries', 'Ligament_Injuries'), ('muscle_injuries', 'Muscle_Injuries'), ('tendon_injuries', 'Tendon_Injuries')], max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
            ],
        ),
    ]
