# Generated by Django 4.2.9 on 2024-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_remove_member_medical_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='custom_duration_days',
        ),
        migrations.AlterField(
            model_name='payment',
            name='programme',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength training', 'Strength Training'), ('strength training & cardio', 'Strength Training & Cardio'), ('personal training', 'Personal Training')], max_length=40, null=True),
        ),
    ]
