# Generated by Django 4.2.9 on 2024-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_remove_payment_custom_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half-Yearly'), ('annual', 'Annual')], max_length=20),
        ),
    ]
