# Generated by Django 4.2.9 on 2024-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_payment_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='arthritis',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('ligament_injuries', 'Ligament_Injuries'), ('muscle_injuries', 'Muscle_Injuries'), ('tendon_injuries', 'Tendon_Injuries')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_pressure',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('normal', 'Normal')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='exercise_history',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='heart_disease',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_history',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='medications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='surgeries',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Medical_and_personal_info',
        ),
    ]
