# Generated by Django 4.2.9 on 2024-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_member_allergies_member_arthritis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='allergies',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('normal', 'Normal')], max_length=100, null=True),
        ),
    ]
