# Generated by Django 4.2.9 on 2024-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_member_allergies_alter_member_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='allergies',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
