# Generated by Django 4.1.13 on 2024-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0062_alter_member_allergies"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_staff_account",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StaffAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_accounts",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
