# Generated by Django 4.1.13 on 2024-08-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0063_userprofile_is_staff_account_staffaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_staff_account",
        ),
        migrations.DeleteModel(
            name="StaffAccount",
        ),
    ]
