# Generated by Django 4.1.13 on 2024-08-22 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0064_remove_userprofile_is_staff_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="users",
            field=models.ManyToManyField(
                related_name="user_profiles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
