# Generated by Django 4.1.13 on 2024-08-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0066_remove_userprofile_users_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for",
                to="users.userprofile",
            ),
        ),
    ]
