# Generated by Django 4.1.13 on 2024-08-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0068_remove_userprofile_default_account_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArchivedMemberHistory",
        ),
    ]
