# Generated by Django 4.1.13 on 2024-08-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0069_delete_archivedmemberhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                (
                    "user_profiles",
                    models.ManyToManyField(
                        related_name="staff_members", to="users.userprofile"
                    ),
                ),
            ],
        ),
    ]
