# Generated by Django 4.1.13 on 2024-08-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0070_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
