# Generated by Django 4.1.13 on 2024-08-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0071_alter_staff_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
