# Generated by Django 4.1.13 on 2024-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0073_alter_member_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
