# Generated by Django 4.1.13 on 2024-08-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0075_subaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="name",
            new_name="username",
        ),
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="staff",
            name="user_profiles",
        ),
        migrations.DeleteModel(
            name="SubAccount",
        ),
        migrations.AddField(
            model_name="staff",
            name="user_profiles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subaccounts",
                to="users.userprofile",
            ),
        ),
    ]
