# Generated by Django 4.1.13 on 2024-08-29 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0076_rename_name_staff_username_staff_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Viber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("is_frozen", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("unique_number", models.PositiveIntegerField(null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="pic/")),
                ("weight", models.CharField(blank=True, max_length=30, null=True)),
                ("height", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "exercise_history",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "medications",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("surgeries", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "heart_disease",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("medical_history", models.CharField(max_length=250, null=True)),
                (
                    "allergies",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("high", "High"),
                            ("normal", "Normal"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "diabetes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("high", "High"),
                            ("normal", "Normal"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "arthritis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no", "No"),
                            ("ligament_injuries", "Ligament_Injuries"),
                            ("muscle_injuries", "Muscle_Injuries"),
                            ("tendon_injuries", "Tendon_Injuries"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
