# Generated by Django 4.1.13 on 2024-09-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0077_viber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=50, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_specific_id", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("phone", models.BigIntegerField(null=True)),
                ("aadhar", models.BigIntegerField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("checkin_datetime", models.DateTimeField(null=True)),
                ("checkout_datetime", models.DateTimeField(null=True)),
                ("persons", models.CharField(max_length=50, null=True)),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("netbanking", "NetBanking"),
                            ("cash", "Cash"),
                            ("debit/credit_card", "Debit/Credit_Card"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("marriage", "Marriage"),
                            ("tour", "Tour"),
                            ("official_work", "Official_Work"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("rooms", models.ManyToManyField(to="users.room")),
                (
                    "user_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
