# Generated by Django 4.1.13 on 2024-09-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0078_room_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="member",
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("upi", "UPI"),
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
