# Generated by Django 4.1.13 on 2024-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0080_userprofile_is_restricted_alter_booking_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_restricted_gym",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("netbanking", "NetBanking"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("cash", "Cash"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
