# Generated by Django 4.1.13 on 2024-09-09 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0082_alter_booking_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="unique_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("upi", "UPI"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time_in", models.TimeField(default=django.utils.timezone.now)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("present", models.BooleanField(default=False)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.staff"
                    ),
                ),
            ],
        ),
    ]
