# Generated by Django 4.1.13 on 2024-09-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0086_staff_is_restricted_staff_is_restricted_gym_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("netbanking", "NetBanking"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("cash", "Cash"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
