# Generated by Django 4.1.13 on 2024-09-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0090_alter_booking_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("netbanking", "NetBanking"),
                    ("cash", "Cash"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
