# Generated by Django 4.1.13 on 2024-09-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0092_alter_booking_payment_alter_staff_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("upi", "UPI"),
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
