# Generated by Django 4.1.13 on 2024-09-15 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0094_alter_booking_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                ("message_content", models.TextField()),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
