# Generated by Django 4.1.13 on 2024-09-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0095_alter_booking_payment_messagetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("netbanking", "NetBanking"),
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="MessageTemplate",
        ),
    ]
