# Generated by Django 4.1.13 on 2024-09-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0096_alter_booking_payment_delete_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="slug",
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("upi", "UPI"),
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
