# Generated by Django 4.1.13 on 2024-09-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0098_alter_booking_payment_alter_booking_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="slug",
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                    ("upi", "UPI"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
