# Generated by Django 4.1.13 on 2024-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0100_alter_booking_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("netbanking", "NetBanking"),
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="batch",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("evening", "Evening"),
                    ("custom batch", "Custom Batch"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="programme",
            field=models.CharField(
                choices=[
                    ("cardio", "Cardio"),
                    ("strength training", "Strength Training"),
                    ("strength training & cardio", "Strength Training & Cardio"),
                    ("personal training", "Personal Training"),
                    ("custom program", "Custom Program"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
