# Generated by Django 4.1.13 on 2024-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0102_remove_userprofile_bio_remove_userprofile_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("netbanking", "NetBanking"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("holding", "Holding")],
                default="completed",
                max_length=10,
            ),
        ),
    ]
