# Generated by Django 4.1.13 on 2024-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0106_alter_booking_payment_alter_member_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="time",
            new_name="time_in",
        ),
        migrations.AddField(
            model_name="attendance",
            name="time_out",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("cash", "Cash"),
                    ("netbanking", "NetBanking"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
