# Generated by Django 4.1.13 on 2024-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0107_rename_time_attendance_time_in_attendance_time_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("netbanking", "NetBanking"),
                    ("cash", "Cash"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
