# Generated by Django 5.1.2 on 2024-10-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0108_alter_booking_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("netbanking", "NetBanking"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
