# Generated by Django 5.1.2 on 2024-11-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0111_alter_booking_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pay_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("debit/credit_card", "Debit/Credit_Card"),
                    ("netbanking", "NetBanking"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
