# Generated by Django 4.1.13 on 2025-05-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_payment_pay_id_alter_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.CharField(choices=[('netbanking', 'NetBanking'), ('cash', 'Cash'), ('debit/credit_card', 'Debit/Credit_Card'), ('upi', 'UPI')], max_length=20, null=True),
        ),
    ]
